/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "tertiary-fixed": "#70f6ff",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#002022",
        "on-tertiary-container": "#00696f",
        "outline-variant": "#4d4632",
        "on-primary": "#3a3000",
        "error-container": "#93000a",
        "on-tertiary": "#00373a",
        "background": "#131313",
        "on-primary-fixed": "#221b00",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#544600",
        "primary": "#fff5dc",
        "inverse-primary": "#705d00",
        "on-primary-container": "#705d00",
        "outline": "#999077",
        "surface-container-high": "#2a2a2a",
        "surface": "#131313",
        "tertiary-fixed-dim": "#00dce7",
        "primary-fixed": "#ffe170",
        "surface-variant": "#353534",
        "on-secondary": "#303030",
        "surface-tint": "#e9c400",
        "on-secondary-fixed-variant": "#474746",
        "on-background": "#e5e2e1",
        "tertiary": "#d8fcff",
        "on-secondary-fixed": "#1b1b1c",
        "surface-dim": "#131313",
        "inverse-surface": "#e5e2e1",
        "secondary-container": "#474746",
        "on-surface-variant": "#d0c6ab",
        "secondary-fixed-dim": "#c8c6c5",
        "primary-container": "#ffd600",
        "surface-container-lowest": "#0e0e0e",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#004f53",
        "surface-bright": "#393939",
        "tertiary-container": "#00f0fc",
        "on-surface": "#e5e2e1",
        "on-error": "#690005",
        "on-secondary-container": "#b7b5b4",
        "inverse-on-surface": "#313030",
        "surface-container-low": "#1c1b1b",
        "surface-container-highest": "#353534",
        "secondary": "#c8c6c5",
        "primary-fixed-dim": "#e9c400",
        "surface-container": "#201f1f"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-gap-md": "20px",
        "touch-target-min": "56px",
        "container-padding": "24px",
        "unit": "8px",
        "stack-gap-sm": "12px",
        "stack-gap-lg": "32px",
        "gutter": "16px"
      },
      "fontFamily": {
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-lg": ["Inter"],
        "headline-md-mobile": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "headline-lg": ["36px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "700"}],
        "body-lg": ["20px", {"lineHeight": "1.5", "letterSpacing": "0.01em", "fontWeight": "400"}],
        "headline-sm": ["22px", {"lineHeight": "1.3", "letterSpacing": "0.01em", "fontWeight": "600"}],
        "headline-md": ["28px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "700"}],
        "label-lg": ["16px", {"lineHeight": "1.4", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "headline-lg-mobile": ["30px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["18px", {"lineHeight": "1.5", "letterSpacing": "0.01em", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
